# Generated by Django 4.0.10 on 2023-09-25 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpaa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bike_score',
            field=models.FloatField(null=True, verbose_name='Bike Score'),
        ),
        migrations.AlterField(
            model_name='property',
            name='transit_score',
            field=models.FloatField(null=True, verbose_name='Transit Score'),
        ),
        migrations.AlterField(
            model_name='property',
            name='walk_score',
            field=models.FloatField(null=True, verbose_name='Walk Score'),
        ),
    ]
