# Generated by Django 4.0.10 on 2023-09-26 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpaa', '0003_property_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='garage',
            field=models.IntegerField(default=0, verbose_name='Garage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='story',
            field=models.IntegerField(default=1, verbose_name='Story'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='year',
            field=models.IntegerField(default=1990, verbose_name='Year'),
            preserve_default=False,
        ),
    ]
