# Generated by Django 4.0.10 on 2023-09-26 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpaa', '0004_property_garage_property_story_property_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='dist',
            field=models.FloatField(default=0, verbose_name='Distance'),
            preserve_default=False,
        ),
    ]
