# Generated by Django 4.0.10 on 2023-09-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpaa', '0005_property_dist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='dist',
            field=models.FloatField(null=True, verbose_name='Distance'),
        ),
    ]
