# Generated by Django 4.0.10 on 2023-09-30 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bpaa', '0006_alter_property_dist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('crime_rating', models.PositiveIntegerField()),
                ('school_rating', models.PositiveIntegerField()),
                ('real_estate_rating', models.PositiveIntegerField()),
                ('demo_rating', models.PositiveIntegerField()),
                ('coordinates', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property', to='bpaa.region'),
        ),
    ]
